export const carData = [
  {
    id: 1,
    make: 'Toyota',
    model: 'Corolla',
    year: 2022,
    color: 'Silver',
    mileage: 20000,
    price: 25000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-cylinder',
    horsepower: 169,
    features: ['Bluetooth', 'Backup Camera', 'Keyless Entry'],
    owners: 1,
    image: 'https://i.ytimg.com/vi/4CTkz7GFnj8/maxresdefault.jpg',
  },
  {
    id: 2,
    make: 'Honda',
    model: 'Civic',
    year: 2021,
    color: 'White',
    mileage: 18000,
    price: 22000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
    engine: '1.5L 4-cylinder',
    horsepower: 158,
    features: ['Apple CarPlay', 'Android Auto', 'Lane Departure Warning'],
    owners: 2,
    image:
      'https://www.cnet.com/a/img/resize/7876dbb5d916180072c8d8e0a4ae8a9f3d303c3d/hub/2021/06/25/7ce0f6be-f64a-4815-8573-c341070a9f40/ogi1-2022-honda-civic-sport-sedan-007.jpg?auto=webp&fit=crop&height=675&width=1200',
  },
  {
    id: 3,
    make: 'Ford',
    model: 'Mustang',
    year: 2020,
    color: 'Red',
    mileage: 15000,
    price: 35000,
    fuelType: 'Gasoline',
    transmission: 'Manual',
    engine: '5.0L V8',
    horsepower: 450,
    features: ['Leather Seats', 'Navigation System', 'Heated Seats'],
    owners: 1,
    image:
      'https://a57.foxnews.com/static.foxnews.com/foxnews.com/content/uploads/2019/08/1200/675/shel1.jpg?ve=1&tl=1',
  },
  {
    id: 4,
    make: 'Chevrolet',
    model: 'Equinox',
    year: 2019,
    color: 'Blue',
    mileage: 30000,
    price: 20000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '1.5L 4-cylinder',
    horsepower: 170,
    features: ['Rearview Camera', 'Blind-Spot Monitoring', 'Wi-Fi Hotspot'],
    owners: 2,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8a-0WGh2BLi-4brmDP4n_Ue209wiv_GCv6GXSealZFA&s',
  },
  {
    id: 5,
    make: 'Nissan',
    model: 'Altima',
    year: 2020,
    color: 'Black',
    mileage: 22000,
    price: 21000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
    engine: '2.5L 4-cylinder',
    horsepower: 188,
    features: [
      'Remote Start',
      'Automatic Emergency Braking',
      'Lane Keeping Assist',
    ],
    owners: 1,
    image:
      'https://hips.hearstapps.com/hmg-prod/images/2019-nissan-altima-12-source-1200x699-1562955653.jpg?crop=0.760xw:0.798xh;0.218xw,0&resize=980:*',
  },
  {
    id: 6,
    make: 'BMW',
    model: '3 Series',
    year: 2021,
    color: 'White',
    mileage: 12000,
    price: 40000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engine: '2.0L 4-cylinder',
    horsepower: 255,
    features: ['Sunroof', 'Adaptive Cruise Control', 'Parking Assistance'],
    owners: 1,
    image:
      'https://www.topgear.com/sites/default/files/2022/09/1-BMW-3-Series.jpg',
  },
  {
    id: 7,
    make: 'Tesla',
    model: 'Model 3',
    year: 2022,
    color: 'Red',
    mileage: 8000,
    price: 45000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    engine: 'Electric Motor',
    horsepower: 322,
    features: [
      'Autopilot',
      'Full Self-Driving Capability',
      'Premium Audio System',
    ],
    owners: 1,
    image:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL58m4RgkEe8AeHK6qu4zxVSQG-dCywyHIGjim7NEUig&s',
  },
  {
    id: 8,
    make: 'Audi',
    model: 'Q5',
    year: 2021,
    color: 'Gray',
    mileage: 15000,
    price: 38000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-cylinder',
    horsepower: 248,
    features: ['Virtual Cockpit', 'Panoramic Sunroof', 'Apple CarPlay'],
    owners: 1,
    image:
      'https://www.team-bhp.com/carpics/2021-audi-q5-facelift/l/exterior/2021-audi-q5-facelift-02.jpg',
  },
  {
    id: 9,
    make: 'Mercedes-Benz',
    model: 'E-Class',
    year: 2020,
    color: 'Silver',
    mileage: 18000,
    price: 42000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-cylinder',
    horsepower: 255,
    features: ['MBUX Infotainment', 'Heated Steering Wheel', 'Air Suspension'],
    owners: 2,
    image:
      'https://www.rushlane.com/wp-content/uploads/2020/03/2020-mercedes-e-class-facelift-debuts-india-launch-1.jpg',
  },
  {
    id: 10,
    make: 'Chevrolet',
    model: 'Tahoe',
    year: 2020,
    color: 'Black',
    mileage: 25000,
    price: 45000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '5.3L V8',
    horsepower: 355,
    features: ['Leather Seats', 'Third-Row Seating', 'Power Liftgate'],
    owners: 2,
    image:
      'https://file.kelleybluebookimages.com/kbb/base/evox/CP/12959/2020-Chevrolet-Tahoe-front_12959_032_1870x910_G1M_cropped.png',
  },
  {
    id: 11,
    make: 'Subaru',
    model: 'Outback',
    year: 2021,
    color: 'Green',
    mileage: 12000,
    price: 32000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
    engine: '2.5L 4-cylinder',
    horsepower: 182,
    features: ['All-Wheel Drive', 'Roof Rails', 'Adaptive Cruise Control'],
    owners: 1,
    image:
      'https://img.sm360.ca/images/article/marino-auto-group/81426//2020_outback_101606420532388.jpg',
  },
  {
    id: 12,
    make: 'Lexus',
    model: 'RX 350',
    year: 2022,
    color: 'White',
    mileage: 8000,
    price: 48000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '3.5L V6',
    horsepower: 295,
    features: [
      'Premium Leather Seats',
      'Panoramic Sunroof',
      'Mark Levinson Audio',
    ],
    owners: 1,
    image:
      'https://www.motortrend.com/uploads/2022/05/2021-Lexus-RX350-F-SPORT-front-three-quarter-1.jpg',
  },
  {
    id: 13,
    make: 'Ford',
    model: 'F-150',
    year: 2020,
    color: 'Blue',
    mileage: 18000,
    price: 38000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '3.5L V6',
    horsepower: 375,
    features: ['Towing Package', 'Off-Road Package', 'Sync 3 Infotainment'],
    owners: 1,
    image: 'https://www.vehiclehistory.com/uploads/2020-Ford-F-150.jpg',
  },
  {
    id: 14,
    make: 'BMW',
    model: 'X5',
    year: 2021,
    color: 'Black',
    mileage: 14000,
    price: 55000,
    fuelType: 'Diesel',
    transmission: 'Automatic',
    engine: '3.0L 6-cylinder',
    horsepower: 335,
    features: ['Heated Seats', 'Wireless Charging', 'Gesture Control'],
    owners: 1,
    image: 'https://hips.hearstapps.com/hmg-prod/images/2021-bmw-x5-xdrive45e-162-1616444506.jpg?crop=0.617xw:0.693xh;0.340xw,0.307xh&resize=768:*',
  },
  {
    id: 15,
    make: 'Honda',
    model: 'CR-V',
    year: 2019,
    color: 'Silver',
    mileage: 25000,
    price: 26000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
    engine: '1.5L 4-cylinder',
    horsepower: 190,
    features: [
      'Adaptive Cruise Control',
      'Lane Keeping Assist',
      'Apple CarPlay',
    ],
    owners: 2,
    image: 'https://www.motortrend.com/uploads/sites/5/2019/01/2019-Honda-CR-V-AWD-front-three-quarter-in-motion-1.jpg',
  },
  {
    id: 16,
    make: 'Toyota',
    model: 'RAV4',
    year: 2020,
    color: 'White',
    mileage: 18000,
    price: 29000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.5L 4-cylinder',
    horsepower: 203,
    features: [
      'Blind-Spot Monitoring',
      'Rear Cross-Traffic Alert',
      'Apple CarPlay',
    ],
    owners: 1,
    image: 'https://global.toyota/pages/news/images/2019/11/20/1405/001.jpg',
  },
  {
    id: 17,
    make: 'Tesla',
    model: 'Model Y',
    year: 2022,
    color: 'Red',
    mileage: 8000,
    price: 52000,
    fuelType: 'Electric',
    transmission: 'Automatic',
    engine: 'Dual Electric Motors',
    horsepower: 384,
    features: ['Autopilot', 'Premium Interior', 'Panoramic Roof'],
    owners: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlQW8ez_YrLiL0P94sm1UJ0gymUOPt4HO9FEbHBQc7xg&s',
  },
  {
    id: 18,
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2019,
    color: 'Black',
    mileage: 25000,
    price: 35000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '5.3L V8',
    horsepower: 355,
    features: ['Towing Package', 'Trailer Brake Controller', 'Apple CarPlay'],
    owners: 2,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS0XPnb1ZSWq96Qx7KHo1ytSeGSkETz-mHvjK6XFCRKkw&s',
  },
  {
    id: 19,
    make: 'Ford',
    model: 'Escape',
    year: 2021,
    color: 'Gray',
    mileage: 12000,
    price: 28000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '1.5L 4-cylinder',
    horsepower: 181,
    features: ['Apple CarPlay', 'Android Auto', 'Blind-Spot Monitoring'],
    owners: 1,
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwqEPKLBQQDbFe5N_o6oYZ1iGcwsBs83q5HiFJxgYBMQ&s',
  },
  {
    id: 20,
    make: 'Mercedes-Benz',
    model: 'GLE 350',
    year: 2020,
    color: 'Silver',
    mileage: 18000,
    price: 46000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-cylinder',
    horsepower: 255,
    features: [
      'MBUX Infotainment',
      'Panoramic Sunroof',
      'Adaptive Cruise Control',
    ],
    owners: 2,
    image: 'https://www.cnet.com/a/img/resize/ddd2d3686d7ce12539d17d09062a5a8544eb3b0a/hub/2020/02/21/7bb52c0b-cb44-4ec7-ad1a-3faa65771249/2020-mercedes-benz-gle350-011.jpg?auto=webp&width=1200',
  },
  {
    id: 21,
    make: 'BMW',
    model: '4 Series',
    year: 2021,
    color: 'Blue',
    mileage: 10000,
    price: 48000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '2.0L 4-cylinder',
    horsepower: 255,
    features: ['Head-Up Display', 'Wireless Charging', 'Parking Assistance'],
    owners: 1,
    image: 'https://images.drivespark.com/img/2020/06/2021-bmw-4-series-coupe-front-profile-1591177973.jpg',
  },
  {
    id: 22,
    make: 'Honda',
    model: 'Accord',
    year: 2022,
    color: 'Black',
    mileage: 8000,
    price: 31000,
    fuelType: 'Gasoline',
    transmission: 'CVT',
    engine: '1.5L 4-cylinder',
    horsepower: 192,
    features: [
      'Honda Sensing Suite',
      'Remote Engine Start',
      'Wireless Phone Charger',
    ],
    owners: 1,
    image: 'https://hips.hearstapps.com/hmg-prod/images/2021-honda-accord-hybrid-mmp-1-1634840672.jpg',
  },
  {
    id: 23,
    make: 'Jeep',
    model: 'Grand Cherokee',
    year: 2021,
    color: 'White',
    mileage: 10000,
    price: 38000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '3.6L V6',
    horsepower: 295,
    features: ['4WD', 'Uconnect Infotainment', 'Heated Seats'],
    owners: 1,
    image: 'https://www.financialexpress.com/wp-content/uploads/2022/10/Jeep-Grand-Cherokee.jpg?w=1024',
  },
  {
    id: 24,
    make: 'Toyota',
    model: 'Highlander',
    year: 2020,
    color: 'Silver',
    mileage: 20000,
    price: 36000,
    fuelType: 'Gasoline',
    transmission: 'Automatic',
    engine: '3.5L V6',
    horsepower: 295,
    features: ['Lane Departure Alert', 'Third-Row Seating', 'Smart Key System'],
    owners: 2,
    image: 'https://hips.hearstapps.com/hmg-prod/images/2023-toyota-highlander-platinum-awd-574-edit-2-641379813f7bf.jpg?crop=0.605xw:0.453xh;0.246xw,0.418xh&resize=640:*',
  },

];
